// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XLKr7txWx8hzb_elTsC8cjKJnccUmEY',
    appId: '1:326002153153:web:5a133f16528c32ba63a640',
    messagingSenderId: '326002153153',
    projectId: 'fir-70-6cc9b',
    authDomain: 'fir-70-6cc9b.firebaseapp.com',
    storageBucket: 'fir-70-6cc9b.appspot.com',
    measurementId: 'G-GM5XYJFG7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUxrmSgbrYJ7WvHUPY-N7gkHinBv_ecc',
    appId: '1:326002153153:android:6063ab0c4207581f63a640',
    messagingSenderId: '326002153153',
    projectId: 'fir-70-6cc9b',
    storageBucket: 'fir-70-6cc9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsikQdd1T3YIPuOe7AgmtUSOWtKPjDJ_M',
    appId: '1:326002153153:ios:07ccf072fe936bf363a640',
    messagingSenderId: '326002153153',
    projectId: 'fir-70-6cc9b',
    storageBucket: 'fir-70-6cc9b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsikQdd1T3YIPuOe7AgmtUSOWtKPjDJ_M',
    appId: '1:326002153153:ios:2a04348ed78273ca63a640',
    messagingSenderId: '326002153153',
    projectId: 'fir-70-6cc9b',
    storageBucket: 'fir-70-6cc9b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
