// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-9GgZzo3U33AScKBCUOjaJJ-Cz2Y-cA',
    appId: '1:126028808699:web:e3d724522dd56b41ff4b5e',
    messagingSenderId: '126028808699',
    projectId: 'chat-app-499e7',
    authDomain: 'chat-app-499e7.firebaseapp.com',
    storageBucket: 'chat-app-499e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbCbtDar412DnTwyepJMHbRa83AzBpt8',
    appId: '1:126028808699:android:ababedd2417a7c3aff4b5e',
    messagingSenderId: '126028808699',
    projectId: 'chat-app-499e7',
    storageBucket: 'chat-app-499e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5i9-F5M75u4mLgILpjdO6_qhHgjUU_w',
    appId: '1:126028808699:ios:4b1664314aad844bff4b5e',
    messagingSenderId: '126028808699',
    projectId: 'chat-app-499e7',
    storageBucket: 'chat-app-499e7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5i9-F5M75u4mLgILpjdO6_qhHgjUU_w',
    appId: '1:126028808699:ios:36782bc43d5d76d1ff4b5e',
    messagingSenderId: '126028808699',
    projectId: 'chat-app-499e7',
    storageBucket: 'chat-app-499e7.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
